-- MySQL Script generated by MySQL Workbench
-- Thu Nov 29 23:49:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel` ;

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` TINYTEXT NULL,
  `role` TINYTEXT NOT NULL,
  `email` TINYTEXT NOT NULL,
  `password_hash` TINYTEXT NOT NULL,
  `status` INT(2) NULL DEFAULT 10,
  `created_at` INT(10) NULL,
  `updated_at` INT(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TINYTEXT NOT NULL,
  `status` INT(2) NULL DEFAULT 10,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TINYTEXT NOT NULL,
  `status` INT(2) NULL DEFAULT 10,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hotel_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `title` TINYTEXT NOT NULL,
  `status` INT(2) NULL DEFAULT 10,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_hotel1_idx` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_room_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_hotel1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `hotel`.`hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `hotel`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `status` INT(2) NULL DEFAULT 10,
  `start` INT(10) NOT NULL,
  `end` INT(10) NOT NULL,
  `total_price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_reservation_room1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hotel`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `hotel`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hotel`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `hotel`;
INSERT INTO `hotel`.`user` (`id`, `full_name`, `role`, `email`, `password_hash`, `status`, `created_at`, `updated_at`) VALUES (1, 'Jan Kowalski', 'ROLE_CLEANERS', 'jan.kowalski@website.domen', 'b1b3773a05c0ed0176787a4f1574ff0075f7521e', 10, 1543665600, 1543665600);
INSERT INTO `hotel`.`user` (`id`, `full_name`, `role`, `email`, `password_hash`, `status`, `created_at`, `updated_at`) VALUES (2, 'Ivan Karbashevskyi', 'ROLE_DIRECKOR', 'ivan.karbashevskyi@hashlink.in.ua', 'b1b3773a05c0ed0176787a4f1574ff0075f7521e', 10, 1543665600, 1543665600);
INSERT INTO `hotel`.`user` (`id`, `full_name`, `role`, `email`, `password_hash`, `status`, `created_at`, `updated_at`) VALUES (3, 'Ewa Popowska', 'ROLE_RECEPTIONIST', 'ewa.popowska@website.domen', 'b1b3773a05c0ed0176787a4f1574ff0075f7521e', 10, 1543665600, 1543665600);
INSERT INTO `hotel`.`user` (`id`, `full_name`, `role`, `email`, `password_hash`, `status`, `created_at`, `updated_at`) VALUES (4, 'Artur Zinowski', 'ROLE_CLIENT', 'artur.zinowski@website.domen', 'b1b3773a05c0ed0176787a4f1574ff0075f7521e', 10, 1543665600, 1543665600);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hotel`.`hotel`
-- -----------------------------------------------------
START TRANSACTION;
USE `hotel`;
INSERT INTO `hotel`.`hotel` (`id`, `title`, `status`) VALUES (1, 'Kolopso', 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hotel`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `hotel`;
INSERT INTO `hotel`.`category` (`id`, `title`, `status`) VALUES (1, 'Standart', 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hotel`.`room`
-- -----------------------------------------------------
START TRANSACTION;
USE `hotel`;
INSERT INTO `hotel`.`room` (`id`, `hotel_id`, `category_id`, `title`, `status`, `price`) VALUES (1, 1, 1, '2 lurzka + bałkon', 10, 85.00);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hotel`.`reservation`
-- -----------------------------------------------------
START TRANSACTION;
USE `hotel`;
INSERT INTO `hotel`.`reservation` (`id`, `user_id`, `room_id`, `status`, `start`, `end`, `total_price`) VALUES (1, 4, 1, 10, 1543665600, 1544443200, 850.00);

COMMIT;

